spring:
  application:
    name: AuthServer
  datasource:
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        use_sql_comments: false
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
